### ISSUE TITLE
Fail to run md5sum

### ISSUE THREAD

**Issue by zhanggenex** [vusec/TIFF#2]
I got a failure when running md5sum (but success in base64, uniq, who).

My input is

> python TIFF/fuzzer-code/runfuzzer.py -s "lava_corpus/LAVA-M/md5sum/coreutils-8.24-lava-safe/build/bin/md5sum -c %s" -i TIFF/fuzzer-code/datatemp/md5/ -w TIFF/fuzzer-code/idafiles/md5sum.pkl -n TIFF/fuzzer-code/idafiles/md5sum.names -l 1 -o "0x0000000000000000"

The error message is
> Just about to run  ['pinplay-1.2-pin-2.13-62732-gcc.4.4.7-linux/pin.sh', '-tool_exit_timeout', '1', '-t', 'TIFF/fuzzer-code/obj-intel64/bbcounts2.so', '-o', 'TIFF/fuzzer-code/outd/bbc.out', '-x', '30', '-libc', '0', '-l', '', '-location', 'TIFF/fuzzer-code/vutemp/data/ex-1.md5', '--', 'lava_corpus/LAVA-M/md5sum/coreutils-8.24-lava-safe/build/bin/md5sum', '-c', 'TIFF/fuzzer-code/vutemp/data/ex-1.md5']
> Starting the app now...
> 
> Run complete..
> 
> looks like we already got a crash!!

Could you please help me with this one?
Thanks a lot.
@tosanjay @vivek425ster

**Comment by tosanjay** [comment]
Yes, md5sum has a problem that makes it crash immediately. there was another paper too that reported it. I am sure that it is a md5sum LAVA binary problem.

**Comment by wzunknown** [comment]
You can test it with some binary format file, `md5sum -c $file`, and it would cause `segmentation fault`.
I solve it by building LAVA-M at another environment (like ubuntu 16.04).
